#ifndef __MONO_DEBUGGER_X86_ARCH_H__
#define __MONO_DEBUGGER_X86_ARCH_H__

#include <glib.h>

G_BEGIN_DECLS

typedef enum {
	DEBUGGER_REG_RAX	= 0,
	DEBUGGER_REG_RCX,
	DEBUGGER_REG_RDX,
	DEBUGGER_REG_RBX,

	DEBUGGER_REG_RSP,
	DEBUGGER_REG_RBP,
	DEBUGGER_REG_RSI,
	DEBUGGER_REG_RDI,

	DEBUGGER_REG_R8,
	DEBUGGER_REG_R9,
	DEBUGGER_REG_R10,
	DEBUGGER_REG_R11,
	DEBUGGER_REG_R12,
	DEBUGGER_REG_R13,
	DEBUGGER_REG_R14,
	DEBUGGER_REG_R15,

	DEBUGGER_REG_RIP,
	DEBUGGER_REG_EFLAGS,

	DEBUGGER_REG_ORIG_RAX,
	DEBUGGER_REG_CS,
	DEBUGGER_REG_SS,
	DEBUGGER_REG_DS,
	DEBUGGER_REG_ES,
	DEBUGGER_REG_FS,
	DEBUGGER_REG_GS,

	DEBUGGER_REG_FS_BASE,
	DEBUGGER_REG_GS_BASE,

	DEBUGGER_REG_LAST
} DebuggerX86Registers;

G_END_DECLS

#endif


